FROM ubuntu:24.04


RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.5 \
    vim \
    python3-pip \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# RUN pip3 install numpy

# Build command: docker build -t test_volume_v1 -f Dockerfile_volume .
# Run container: docker run -it -v "$PWD":/data test_volume_v1

